category = {
    
    "laptops-laptops-computers":"Laptops",                                               
    "ultrabooks-laptops-computers":"Ultrabooks",
    "mac-computers-laptops":"Mac Computers",
    "all-in-one-laptops-computers":"All in One",
    "pendrives":"Pendrives",
    "servers":"Servers",
    "peripherals":"Peripherals",
    "gaming-laptops-computers":"Gaming",
    "accessories-laptops-computers":"Accessories",
    "audio-speakers":"Audio Speakers",
    "headphones":"Headphones",
    "computer-cases":"Computer Cases",
    "printers":"Printers",
    "cameras":"Cameras",
    "smartphones":"Smartphones",
    "game-consoles":"Game Consoles",
    "power-banks":"Power Banks",
    "smartwatches":"Smartwatches",
    "chargers":"Chargers",
    "cases":"Cases",
    "headphone-accessories":"Headphone Accessories",
    "headphone-cases":"Headphone Cases",
    "tablets":"Tablets",
    "tvs":"TVs",
    "wearables":"Wearables",
}    
    