"""
Django settings for OneTech project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$7vwp$6=^ugvi1!rod(!jyknw$gwj5#bppft)+k4wo)u2os*o)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home.apps.HomeConfig',
    'categories.apps.CategoriesConfig',
    'article.apps.ArticleConfig',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'contact.apps.ContactConfig',
    'asset',
    'crispy_forms',
    'account.apps.AccountConfig',
    'wishlist.apps.WishlistConfig',
    'ckeditor',
    'ckeditor_uploader',
    'stripe'
    

]

CKEDITOR_UPLOAD_PATH = 'upload/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OneTech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OneTech.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL ='home'

LOGIN_URL = 'login'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nofees202@gmail.com'
EMAIL_HOST_PASSWORD = 'Rotondwa2+'

# Stripe and Braintree Settings

if DEBUG:
    # test keys
    STRIPE_PUBLISHABLE_KEY = 'pk_test_51GxsxUJSMWtivThyF8AmTavuuthGuJcTsfoCBVcBeyZCuTXbe8nUHv9msLvdKcCjpZqVTi6LFINhc2MM6GIatHsy00nhAUwU0d'
    STRIPE_SECRET_KEY = 'sk_test_51GxsxUJSMWtivThyB17edEYOsAm8iqlFsD5lKwcDMVWssJPJm7q1F57x1xY4ZmpJvUN68LgIOeAGVPkr2sAwoVHh00S8w3a70M'
else:
    # live keys
    STRIPE_PUBLISHABLE_KEY = 'pk_test_51GxsxUJSMWtivThyF8AmTavuuthGuJcTsfoCBVcBeyZCuTXbe8nUHv9msLvdKcCjpZqVTi6LFINhc2MM6GIatHsy00nhAUwU0d'
    STRIPE_SECRET_KEY = 'sk_test_51GxsxUJSMWtivThyB17edEYOsAm8iqlFsD5lKwcDMVWssJPJm7q1F57x1xY4ZmpJvUN68LgIOeAGVPkr2sAwoVHh00S8w3a70M'

