# Generated by Django 2.2 on 2020-07-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200704_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrderItem',
        ),
    ]
